### ISSUE TITLE
Memory  Leakage Issue

### ISSUE THREAD

**Issue by DaeHyeonNam** [Sovahero/PluginMobileNativeCode#10]
Hi! Thanks for the great plugin.
While I was using your plugin, I faced a memory leakage issue. The issue happens when I use JNI calls more than  10K times because memory overflows. And when I used android project to debug, I think the memory is leaking in your plugin side. Especially the below codes.
![image](https://user-images.githubusercontent.com/40844251/123955457-988bc600-d9e4-11eb-9ba0-f110812099c0.png)
In the code, you only make global reference without deleting it.

**Comment by DaeHyeonNam** [comment]
I solved it by deleting global reference. To do that, you need to modify the parameter pack things that some functions have. After calling Java code, you can delete global ref.

**Comment by Entilzar** [comment]
Sorry, I am no expert in Android development.
Can you elaborate on how to fix the issue ? Do you have an example ?
The "you need to modify the parameter pack things that some functions have" eludes me, and I don't know where to delete the global ref .

**Comment by DaeHyeonNam** [comment]
> Sorry, I am no expert in Android development. Can you elaborate on how to fix the issue ? Do you have an example ? The "you need to modify the parameter pack things that some functions have" eludes me, and I don't know where to delete the global ref .

Oh gotcha. I haven't worked on this project for a while since I solved this issue. I will try to look up my codes again and get back to you tmr. Please remind me if I do not come out.

**Comment by Sovahero** [comment]
> > Sorry, I am no expert in Android development. Can you elaborate on how to fix the issue ? Do you have an example ? The "you need to modify the parameter pack things that some functions have" eludes me, and I don't know where to delete the global ref .
> 
> Oh gotcha. I haven't worked on this project for a while since I solved this issue. I will try to look up my codes again and get back to you tmr. Please remind me if I do not come out.

It would be great if you share the pieces of code that need to be fixed. Unfortunately, I didn't have time to study this problem)
