### ISSUE TITLE
Getting "Undefined symbols for architecture arm64" build error when trying to package iOS project that uses async callbacks

### ISSUE THREAD

**Issue by cdmoss** [Sovahero/PluginMobileNativeCode#11]
First I'd like to say that this has been an amazing plugin, so I hope it is still somewhat monitored .

As the title says, I'm getting the following error when trying to package an iOS project:

```
Undefined symbols for architecture arm64:
UATHelper: Packaging (iOS):       "UMobileNativeCodeBlueprint::SpeechRecognitionCallbackIOS(NSString*)", referenced from:
UATHelper: Packaging (iOS):           -[SpeechRecorderViewController levelTimerCallback:] in SpeechRecorderViewController.mm.o
UATHelper: Packaging (iOS):     ld: symbol(s) not found for architecture arm64
UATHelper: Packaging (iOS):     clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

As shown in the message, trying to include the iOS callback inside my .mm file causes the error. I've set up the dispatcher correctly it seems as I have no problems with the Android side. From what I can tell, I've implemented it exactly the same as is done in the sample code: 

- I've declared a stub in MobileNativeCodeBlueprint.h like so: 
```
#if PLATFORM_IOS
    static void SpeechRecognitionCallbackIOS(NSString* sResult);
    #endif
```

- I've defined the Callback method in MobileNativeCodeBlueprint.cpp like so: 
```
#if PLATFORM_IOS
void SpeechRecognitionCallbackIOS(NSString* sResult)
{
  FString fResult = FString(sResult);
  UE_LOG(LogTemp, Warning, TEXT("asyncHelloWorld callback caught in C++! - [%s]"), *FString(fResult)); //Debug log for UE4
  UMobileNativeCodeBlueprint::SpeechResultsDispatch(fResult); // Call Dispatcher
}
#endif
```

- I've included the #include "MobileNativeCodeBlueprint.h" statement at the top of the corresponding .mm file in order to bring the callback into scope.

Could anyone shed some light into what might be be causing the error? Or whether or not I'm missing something?

**Comment by Sovahero** [comment]
Calling a static function from .mm is no different if it were called from C++. Therefore, it is very strange that when declaring "MobileNativeCodeBlueprint.h" in the "SpeechRecorderViewController.mm" your code doesn't see `UMobileNativeCodeBlueprint::SpeechRecognitionCallbackIOS`. Try from the "SpeechRecorderViewController.mm" call the standard plugin function `UMobileNativeCodeBlueprint::CallBackCppIOS("@"ExampleText");`
