### ISSUE TITLE
Error in sending jobjectArray

### ISSUE THREAD

**Issue by Respirant** [Sovahero/PluginMobileNativeCode#2]
When I try to define "jobjectArray" variable to define the exact Java function, I have this error:
`Error: cannot initialize return object of type '_jobjectArray *' with an rvalue of type 'jobject' (aka '_jobject *')`

It looks like arrays are not implemented in Android JNI at all, it is?

**Comment by Sovahero** [comment]
> Когда я пытаюсь определить переменную "jobjectArray", чтобы определить точную функцию Java, у меня возникает эта ошибка:
> `Error: cannot initialize return object of type '_jobjectArray *' with an rvalue of type 'jobject' (aka '_jobject *')`
> 
> Похоже, массивы вообще не реализованы в Android JNI, так ли это?

Yes, arrays are not implemented.

In order for the Java function to accept jobjectArray you need to AndroidUtils.cpp -> line 165, add a new GetTypeName function that will return "[Ljava.lang. Object;". Before calling CallNativeAndroidVoid, you need to convert the C++ variable to jobjectArray. In JavaConvert.cpp it shows how you can convert different data types from Java to C++.

To return a jobjectarray variable from Java to c++, you need to AndroidUtils.cpp - > line 239 add 2 new functions. 1 function: jobjectArray AndroidUtils:: CallJNI (jobjectArray), constant type char* class name, constant type char* Method_name, constant type char* MethodSignature, Arguments ...arguments), this function must call function 2: CallJniObjectArrayMethod(class, Methodname, MethodSignature, args parameter...);. You should implement the second function yourself using examples AndroidUtils.cpp - > line 4-106

**Comment by Respirant** [comment]
> > Когда я пытаюсь определить переменную "jobjectArray", чтобы определить точную функцию Java, у меня возникает эта ошибка:
> > `Error: cannot initialize return object of type '_jobjectArray *' with an rvalue of type 'jobject' (aka '_jobject *')`
> > Похоже, массивы вообще не реализованы в Android JNI, так ли это?
> 
> Yes, arrays are not implemented.
> 
> In order for the Java function to accept jobjectArray you need to AndroidUtils.cpp -> line 165, add a new GetTypeName function that will return "[Ljava.lang. Object;". Before calling CallNativeAndroidVoid, you need to convert the C++ variable to jobjectArray. In JavaConvert.cpp it shows how you can convert different data types from Java to C++.
> 
> To return a jobjectarray variable from Java to c++, you need to AndroidUtils.cpp - > line 239 add 2 new functions. 1 function: jobjectArray AndroidUtils:: CallJNI (jobjectArray), constant type char* class name, constant type char* Method_name, constant type char* MethodSignature, Arguments ...arguments), this function must call function 2: CallJniObjectArrayMethod(class, Methodname, MethodSignature, args parameter...);. You should implement the second function yourself using examples AndroidUtils.cpp - > line 4-106

Thank you for the answer. I did everything you wrote, but I have this error:
`Private/Android/Utils/AndroidUtils.cpp(305,33): error: variable 'returnType' is uninitialized when used here [-Werror,-Wuninitialized]`
It seems that function "AndroidUtils::CallNativeAndroid" can't get "MethodType returnType" of the variable "jobjectArray"

I have this code in "[PluginName]BPLibrary.cpp":
`TArray<FString> MusicInf = JavaConvert::ConvertToStringArray(AndroidUtils::CallNativeAndroid<jobjectArray>("com/epicgames/ue4/TestJavaClass", "GetFileInfo", false, FilePath));`

And these functions in "AndroidUtils.cpp":
1) 
`// ------------ jobjectArray
template<typename ...Args>
jobjectArray AndroidUtils::CallJNI(jobjectArray joa, const char* ClassName, const char* MethodName, const char* MethodSignature, Args ...args)
{
	return CallJniObjectArrayMethod(ClassName, MethodName, MethodSignature, args...);
}
`
2) 
`jobjectArray AndroidUtils::CallJniObjectArrayMethod(const ANSICHAR* ClassName, const ANSICHAR* MethodName, const ANSICHAR* MethodSignature, ...)
{
	UE_LOG(LogTemp, Warning, TEXT("Method CallJni [%s][%s]"), *FString(MethodName), *FString(MethodSignature));
	JNIEnv* Env = FAndroidApplication::GetJavaEnv();
	jclass Class = FAndroidApplication::FindJavaClass(ClassName);
	jmethodID Method = FJavaWrapper::FindStaticMethod(Env, Class, MethodName, MethodSignature, false);
	va_list Args;
	va_start(Args, MethodSignature);
	jobjectArray Result = (jobjectArray)Env->CallStaticObjectMethodV(Class, Method, Args);
	va_end(Args);
	Env->DeleteLocalRef(Class);
	return Result;
}`

What do you think?

**Comment by Sovahero** [comment]
Can you write your JAVA function "GetFileInfo" here?

**Comment by Respirant** [comment]
Yes, for sure.

Here is it:

`import android.media.MediaMetadataRetriever;
...
@Keep
	public static String[] GetFileInfo(final String FilePath) {
		MediaMetadataRetriever mmr = new MediaMetadataRetriever();
		mmr.setDataSource(FilePath);
		String Duration = mmr.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION);
		String Artist = mmr.extractMetadata(MediaMetadataRetriever.METADATA_KEY_ARTIST);
		String[] FileInformation = { Duration, Artist };
		return FileInformation;
	}`

**Comment by Respirant** [comment]
Here is the link where the C++ and Java code is more structured, maybe it will be easier to look here - https://gist.github.com/Respirant/b3c8e580c8a4cf2ff60e161721fb258e

**Comment by Sovahero** [comment]
I added a new commit, in "PluginNameBPLibrary.cpp" the ExampleArray() function shows working with arrays. In your case, TArray<FString> MusicInf = AndroidUtils:: CallNativeAndroid<TArray<FString>>("com/epicgames/ue4/TestJavaClass", "GetFileInfo", false, FilePath);

**Comment by Respirant** [comment]
> I added a new commit, in "PluginNameBPLibrary.cpp" the ExampleArray() function shows working with arrays. In your case, TArray MusicInf = AndroidUtils:: CallNativeAndroid<TArray>("com/epicgames/ue4/TestJavaClass", "GetFileInfo", false, FilePath);

Wow, that is awazing, thank you very much!
