### ISSUE TITLE
Another error related to arrays

### ISSUE THREAD

**Issue by Respirant** [Sovahero/PluginMobileNativeCode#3]
Hello, I tried to fully delete this plugin from the project and set up it again, I didn't add any code, I only add these nodes:
![image](https://user-images.githubusercontent.com/69837452/99525862-b4cd7c00-299a-11eb-92f9-bd8134174b92.png)

The node "Example Array" is the same as you created. There was no errors during the compilation, but an application crashes down when the function "Example Array" is executed. I tried to debug this error in Android Studio and get some errors related to JniArray:
![image](https://user-images.githubusercontent.com/69837452/99526101-14c42280-299b-11eb-84f8-954381fe9232.png)

Could you please try to check it out and review your functions related to getting JNI Array, because this error is the same even in an empty project without any plugin changes.

**Comment by Sovahero** [comment]
This is strange, before I uploaded commit, I checked it on version 4.24.3-ndk-14r-nexus 5 and version 4.25.4-ndk - 21b-honor play. When calling this node, my app didn't crash. Have you deleted the "Intermediate" folder from your project directory?

**Comment by Sovahero** [comment]
[https://drive.google.com/file/d/1m0xkDiUUUSpR9Joj6ZHSxPTZ-57Gqoba/view?usp=sharing](url) Try running this project, it already has a plugin. Choose one of the versions (4.24 or 4.25).

**Comment by Respirant** [comment]
Thank you very much, I really appreciate it, I will test.
If it's not a secret, do you have a Telegram or another account? It would be awesome to talk about anything related to programming specifically or in general.

My Telegram is @Respirant

**Comment by Respirant** [comment]
I tried to run your project, and it works fine! Yes, the problem was occured 'cause of the "Intermediate" folder. Thanks a lot 👍
