### ISSUE TITLE
Error in initializing bool variable type

### ISSUE THREAD

**Issue by Respirant** [Sovahero/PluginMobileNativeCode#4]
Hello. Since it is necessary that the type of the variable was initialized before the GetTypeName method inside CallNativeAndroid, a variable of type bool is not initialized by default, and therefore, when trying to call a function that should return bool, an error occurs:

![fkrswx4](https://user-images.githubusercontent.com/69837452/103990719-ba795e00-51a2-11eb-9da0-45473d35cbc6.png)

This is how the code for calling the function looks like
![R4rva1b](https://user-images.githubusercontent.com/69837452/103990862-ed235680-51a2-11eb-9c42-11c935068972.png)

To solve this problem, it is needed to initialize bool in CallNativeAndroid method, but I don't know how to do this without redefining the bool engine type of the variable. Maybe you have any ideas how to do this?

**Comment by Sovahero** [comment]
Hi, I checked and yes an error occurs if I try to return the bool variable.
In AndroidUtils.cpp add {}, after MethodType ReturnType
![image](https://user-images.githubusercontent.com/53889054/104084802-43a89780-526c-11eb-8f9d-80356507d2b0.png)

**Comment by Sovahero** [comment]
Added a new commit, fixed the bool, and merged CallNativeAndroidVoid and CallNativeAndroid<Type> in a single function CallJavaCode<ReturnTypе>. Now you can write CallJavaCode<Void>

**Comment by Respirant** [comment]
Yes, it works, thanks a lot.
