### ISSUE TITLE
Not an issue, I'd like to offer you a job

### ISSUE THREAD

**Issue by andrster1** [Sovahero/PluginMobileNativeCode#5]
Sorry for reaching out like this, but you don't have any contact info. Would you be interested in a minor UE4-Android task? Of course there will be compensation for your work. 

Thank you in advance

**Comment by Sovahero** [comment]
Hi, I'm afraid I won't have time to take on a new job. But if you have any questions about android, I will try to answer them in Discrod: MihailRogozhnikov#7652
