### ISSUE TITLE
Catch the SplashActivity instead of GameActivity in CallJNI

### ISSUE THREAD

**Issue by chatz91** [Sovahero/PluginMobileNativeCode#6]
Hello, 
I have been trying to use your plugin in order to open my UE4 app from another android app while also passing to it a string data through the Extras field. In the AndroidUtils.cpp I can see IsTypeJNI method that calls the 
CallJNI with the argument FJavaWrapper::GameActivityThis. Do you know of a way to handle the SplashActivity instead, so I can catch the intent and extract the string data? Thanks in advance.

**Comment by Sovahero** [comment]
Hi,
I haven’t come across SplashActivity yet, but you can overload the “AndroidUtils :: isTypeJNI (type <MyType> ...” function with your own type and instead of “FJavaWrapper :: GameActivityThis” in the new function pass the Activity that you need as the first parameter (and  his signature).

**Comment by Sovahero** [comment]
You can also transfer a string data type from one application to another by serializing and deserializing the file (.bin or .txt). It is better to save them in a temporary folder provided by the application (function: GetAbsolutePathTmpFolder)

**Comment by chatz91** [comment]
Thanks for your valuable feedback
