### ISSUE TITLE
Request for example of using activity or service.

### ISSUE THREAD

**Issue by DaeHyeonNam** [Sovahero/PluginMobileNativeCode#8]
Hi! Thanks for sharing the great work!
I was trying to use non-static java function but my app is killed when I ran it.
Can you tell me how to use non-static java function(that starts without static indicator)? 
Thanks in advance~!

**Comment by Prikalel** [comment]
same trouble

**Comment by Sovahero** [comment]
The plugin has the ability to use non-static Java functions. To do this, you need to call the first static function to return to the jobject of your Java class. In MobileUtilsBluprint.cpp in the function UMobileNativeCodeBlueprint::ExampleMyJavaObject shows an example, also in the README there is a separate paragraph with pictures about it.
