### ISSUE TITLE
android:requestLegacyExternalStorage not found.

### ISSUE THREAD

**Issue by vediban** [Sovahero/PluginMobileNativeCode#9]
PackagingResults: Error: attribute android:requestLegacyExternalStorage not found.
PackagingResults: Error: failed processing manifest.

When packaging this error occurs. How can I solve it?

**Comment by Sovahero** [comment]
Delete the line: `<addAttribute tag="application" name="android:requestLegacyExternalStorage" value="true"/>` in PluginMobileNativeCode/MobileNativeCode/Source/MobileNativeCode/MobileNativeCode_UPL_Android.xml

This string is no longer needed and is no longer supported by Google
